name: Deploy to Azure Function App

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a requirements.txt file in your repo

    - name: Azure Functions Action - Deploy
      uses: Azure/functions-action@v1
      with:
        app-name: <your-function-app-name>  # Replace with your Azure Function App name
        publish-profile: |
          <?xml version="1.0" encoding="utf-8"?>
          <publishData>
            <publishProfile profileName="Azure App Service" ...>
            <!-- Paste the entire content of the publish profile here -->
            </publishProfile>
          </publishData>
