name: Daily Pipeline

on:
  schedule:
    - cron: '0 6 * * *'  # This schedules the workflow to run every day at 6 AM UTC.
  
jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Assuming you are running tests
