name: Sync Azure DevOps Repo to GitHub

on:
  push:
    branches:
      - main  # Trigger action on push to main branch
  schedule:
    - cron: '0 * * * *'  # Optionally, run the sync every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.GITHUB_REPO_URL }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone Azure DevOps repository
      run: |
        git clone https://$AZURE_DEVOPS_PAT@${{ secrets.AZURE_REPO_URL }} azure-repo
        cd azure-repo
        git fetch --all
        git checkout main  # Assuming you want to sync the `main` branch
        git pull origin main

    - name: Push to GitHub repository
      run: |
        cd azure-repo
        git remote add github https://$GITHUB_TOKEN@${{ secrets.GITHUB_REPO_URL }}
        git push github main --force  # Force push the latest code to GitHub

    - name: Clean up
      run: |
        rm -rf azure-repo
